version: '3'

services:
  # node-app:
  #   build: .
  #   image: node-app
  #   environment:
  #     - NODE_ENV=development
  #     - PORT=3000
  #     - DB_HOST=mysql
  #     - DB_USER=root
  #     - DB_PASSWORD=password
  #     - DB_NAME=node_app
  #     - DB_PORT=3306
  #   ports:
  #     - '3000:3000'
  #   depends_on:
  #     - mysql
  #   volumes:
  #     - .:/usr/src/node-app
  #     - /usr/src/node-app/node_modules
  #   networks:
  #     - node-network
  #   command: npm run dev
  #   restart: unless-stopped

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root@12
      - MYSQL_DATABASE=school_app
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin12#$
    ports:
      - '3306:3306'
    volumes:
      - './docker/db/data:/var/lib/mysql'
      - './docker/db/my.cnf:/etc/mysql/conf.d/my.cnf'
      - './docker/db/sql:/docker-entrypoint-initdb.d'
    networks:
      - node-network
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped

  # Optional phpMyAdmin for database management through the browser
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=root@12
    ports:
      - '8080:80'
    networks:
      - node-network
    depends_on:
      - mysql

volumes:
  mysql-data:

networks:
  node-network:
    driver: bridge